on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  tests:
    name: check Eslint on push
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
